/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import data.Persistencia;
import domain.Especie;
import java.util.InvalidPropertiesFormatException;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


/**
 *
 * @author Litt
 */
public class IngresarAnimalView extends javax.swing.JFrame {

    /**
     * Creates new form IngresarAnimal
     */
    public IngresarAnimalView() {
        initComponents();
        filtro(EdadField1, "NUMERO");
        filtro(PesoField2, "NUMERO");
        filtro(PaisField3, "TEXTO");
        filtro(ISOField4,"TEXTO");
        filtro(ValorFijoField5,"NUMERO");
        
    }

        private void filtro (javax.swing.JTextField campotexto, String opcion){
    ((javax.swing.text.AbstractDocument) campotexto.getDocument()).setDocumentFilter(new javax.swing.text.DocumentFilter() {
    
    @Override
    public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
        
        switch (opcion){
            case "TEXTO" -> {
                if (text.matches("[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ ]+")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
            case "NUMERO" -> {
                if (text.matches("\\d+")) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
                    
        }
        
    }
});
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        EdadField1 = new javax.swing.JTextField();
        PesoField2 = new javax.swing.JTextField();
        PaisField3 = new javax.swing.JTextField();
        ISOField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TipojLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ValorFijoField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        AptitudLabel8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese Datos del Animal");

        jButton2.setText("Cargcar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EdadField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Animales ", "Jirafa", "León", "Elefante", "Tigre" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Edad:");

        jLabel3.setText("Peso");

        jLabel4.setText("Pais");

        jLabel5.setText("ISO");

        jLabel6.setText("Especies:");

        jLabel7.setText("Alimentacion:");

        TipojLabel8.setText("#####");

        jLabel9.setText("Valor Fijo");

        ValorFijoField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorFijoField5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sectores", "Sector 1 ", "Sector 2", "Sector 3", "Sector 4", " " }));

        AptitudLabel8.setText("####");

        jLabel8.setText("Validez:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PaisField3)
                            .addComponent(PesoField2)
                            .addComponent(EdadField1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ISOField4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TipojLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorFijoField5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AptitudLabel8)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdadField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(TipojLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaisField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISOField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(ValorFijoField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AptitudLabel8)
                    .addComponent(jLabel8))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdadField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadField1ActionPerformed

    
    String alimentacion = new String();
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String especie = (String) jComboBox1.getSelectedItem();
        
        if("Seleccionar especie...".equals(especie))
        {
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una especie..."}));
        }
        else if("Jirafa".equals(especie) || "Elefante".equals(especie))
        {
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sectores" ,"Sector 1", "Sector 3"}));
            alimentacion = "Herbívoro";
        }
        else if("León".equals(especie) || "Tigre".equals(especie))
        {
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sectores" ,"Sector 2", "Sector 4"}));
            alimentacion = "Carnívoro";
        }
        TipojLabel8.setText(alimentacion);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ValorFijoField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFijoField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorFijoField5ActionPerformed

    
        double Peso;
        int Edad;
        String Pais;
        int NumeroEspecie=-1;
        int NumeroSector;
        int Estado=-1;
        String[] especiesConvert= {"León", "Jirafa", "Tigre", "Elefante"};
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if((PesoField2.getText()!="") & (EdadField1.getText()!="") & (PaisField3.getText()!="") & (jComboBox1.getSelectedItem()!="Animales") & (jComboBox2.getSelectedItem()!="Sectores"))
        {
            
            AptitudLabel8.setText("Control");
            Peso = Double.parseDouble(PesoField2.getText());
            Edad = Integer.parseInt(EdadField1.getText());
            Pais = PaisField3.getText();
            
            for(int i=0 ; i<4 ; i++)
            {
                if(especiesConvert[i].equals(jComboBox1.getSelectedItem()))
                {
                    NumeroEspecie=i;
                    break;
                }
            }
            
            if(NumeroEspecie==-1){
            System.out.println("Especie no encontrada");
            }
            else
            {
            
            String auxiliar = (String) jComboBox2.getSelectedItem();
            NumeroSector = Character.getNumericValue(auxiliar.charAt(7))-1;
            
            Especie esp = Persistencia.getEspecie(NumeroEspecie);
            
            if(Estado==-1){
            if(esp.getTipoAlimentacion().esCarnivoro()){
                try {
                    Persistencia.addAnimal(Edad, Peso, NumeroEspecie, NumeroSector, 0, PaisField3.getText(), ISOField4.getText());
                    System.out.println("Animal creado");
                } catch (InvalidPropertiesFormatException ex) {
                    System.out.println(ex);
                }
                }else if(esp.getTipoAlimentacion().esHerbivoro()){
                    
                    javax.swing.JOptionPane.showMessageDialog(null, "ES HERBIVORO INGRESE UN VALOR FIJO.");
                    jLabel7.setVisible(true);
                    ValorFijoField5.setVisible(true);
                    Estado=1;
                    
                }
            }else if(!ValorFijoField5.getText().equals("")){
                try {
                    Persistencia.addAnimal(Edad, Peso, NumeroEspecie, NumeroSector, Double.parseDouble(ValorFijoField5.getText()), PaisField3.getText(), ISOField4.getText());
                    System.out.println("Animal Agregado");
                    
                    AptitudLabel8.setText("Apto");
                    
                    Estado=-1;
                    jLabel9.setVisible(false);
                    ValorFijoField5.setVisible(false);
                } catch (InvalidPropertiesFormatException ex) {
                    System.out.println(ex);
                }             
            }
            }
                
            
            }else{
                AptitudLabel8.setText("No apto");}
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarAnimalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AptitudLabel8;
    private javax.swing.JTextField EdadField1;
    private javax.swing.JTextField ISOField4;
    private javax.swing.JTextField PaisField3;
    private javax.swing.JTextField PesoField2;
    private javax.swing.JLabel TipojLabel8;
    private javax.swing.JTextField ValorFijoField5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
